name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "Flow.Launcher.Plugin.RobloxDocs" ]

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Flow.Launcher.Plugin.RobloxDocs/plugin.json'
          prop_path: 'Version'

      - name: Setup .Net
        uses: 'actions/setup-dotnet@v4'
        with:
          dotnet-version: 7.0.x
      
      - name: Restore Dependencies
        run: |
          cd Flow.Launcher.Plugin.RobloxDocs
          dotnet restore
        
      - name: Build
        run: |
          dotnet publish Flow.Launcher.Plugin.RobloxDocs -c Release -r win-x64 -o "build"
          7z a -tzip "Flow.Launcher.Plugin.RobloxDocs-${{ steps.version.outputs.prop }}.zip" "./build/*"
      
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: Flow.Launcher.Plugin.RobloxDocs-${{ steps.version.outputs.prop }}.zip
          tag_name: "v${{steps.version.outputs.prop}}"
